### PR TITLE
Hello

### PR DESCRIPTION
**Pull request by brothman01**
Hello tai!
I have been using your plugin for several years and it has been useful to me as a programmer on many occasions.  I see that the plugin has not been updated in the WordPress Plugin Repository for a few months and I want to help because you have done a good thing inventing this plugin.  I cannot push to the WordPress Plugin Repository but at least you have new code for if you decide to.  Although my contributions today are not very extensive, I want to help keep this plugin maintained and up to date.

**Contributions:**
- I refactored the code
- I erased old comments
- I added doc comments
- I changed function names for grammatical clarity
- I incremented the "Tested Up To" as well as the version in the readme file and in the main file so that users know that the plugin is scrupulously maintained and tested.
- Performed code linting using the current WordPress Standards so that the code is compliant.

If there are any features you would like me to add, please let me know.  I am a developer and if you want to discuss any development or this plugin any further, please tell me.

Thank you.

### CODE REVIEW

**Comment by brothman01** [comment]
@tekapo will you please review and merge my changes?

**Comment by tekapo** [comment]
Hello!

Thank you for the PR!

I was wondering why you change "File_Name" to "Filename".
Is it better English to use "Filename" instead of "File_Name"?
I'm not a native English speaker so I'm just curious!  ;-)

**Comment by brothman01** [comment]
Yes, good question, that is why. Technically, "file name", is accurate, but people were saying those two words together so often that a new word "filename" was officially created to save space on the page to refer to that attribute of a file. As someone who reads many technical computer articles, I can tell you that native English speaking authors use "filename" rather than "file name". 

https://www.dictionary.com/browse/filename

This change of the function name is a minor change to the nice code. Your english is quite good and looks natural. Did you study the language long?

**Comment by brothman01** [comment]
I'm planning to submit a new feature on this PR tonight. Is this branch name ok or should I name it something specific?

**Comment by brothman01** [comment]
@tekapo ok I added the new feature (enqueued styles and scripts are added to the menu color-coded by file type) and fixed a few other minor issues in the plugin (doc comments, etc).  If you approve the changes the PR is ready to be merged.

**Pull request closed without merging**
